### PR TITLE
Introduces writeToTransport as a wrapper for tracking writes and completions. Fixes #154

### LINKED ISSUE #154: An async write operation completion problem
The problem begins here: https://github.com/rwaldron/johnny-five/issues/1306 (important to read through to my findings at the end). 

Summary points: 

- serialport writing is non-blocking
- firmata.js dependent programs may want to do cleanup tasks before exiting.
- firmata.js needs a simple way to signal that writes are: 
  - pending
  - complete
- incrementing and decrementing a counter is simple way to achieve such signaling.

### PR DESCRIPTION
**Pull request by rwaldron**
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>

### CODE REVIEW

**Comment by rwaldron** [comment]
Pending #157

**Comment by rwaldron** [comment]
Rebased

**Comment by soundanalogous** [comment]
I've read through the relevant issue and this solution LGTM.

**Comment by rwaldron** [comment]
Thanks @soundanalogous!

**Pull request merged**
